### PR TITLE
Customize for Giant Swarm usage

### PR DESCRIPTION
**Pull request by tfussell**
`go-changelog` is a tool developed by hashicorp for generating release notes automatically. I plan to use it in our GitHub workflows so we don't have to manually edit `CHANGELOG.md`.

Summary of changes compared with upstream:
- Add CI for test and push to docker
- Add git to docker image
- Update README with relevant changes
- Edit changelog template to be similar to Cluster API
- Make GITHUB_TOKEN optional for testing
- Adjust change types to match GS needs
- Write changelog to file for use with https://github.com/stefanzweifel/git-auto-commit-action
- Add tests
- Restrict allowed format to `release-note:<type>` only
- More error handling

### CODE REVIEW

**Comment by fiunchinho** [comment]
This looks nice. Do you think it will be easy to keep our fork in sync with upstream with all these changes?

**Comment by tfussell** [comment]
> This looks nice. Do you think it will be easy to keep our fork in sync with upstream with all these changes?

It's basically a finished project. There was only one upstream commit since I forked this repo last year and I was able to use built-in functionality to pull in the changes (I've since moved changes to this branch and force pushed `master` so you can't actually see that in the history though). I wouldn't worry too much about it--the whole thing is a few hundred lines of code.

**Review by fiunchinho — APPROVED** [review]

**Review by MarcelMue — APPROVED** [review]

**Review by TheoBrigitte — COMMENTED** [review]
Why do we need to keep a fork of this repository ? Can't we just use upstream ?

**Comment by tfussell** [comment]
> Why do we need to keep a fork of this repository ? Can't we just use upstream ?

You can see all of the changes I made. Compared with upstream, we need CircleCI config, different templates, different categories of changes, different GitHub messages, support for writing to file, different README, some bug fixes. It might make sense to move this code into architect at some point, but I just want something that works for now.

**Pull request merged**
